export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const AUTHENTICATE_STUDENT = "authenticate_student";
export const STUDENT_DETAILS = "student_details";
export const EDIT_STUDENT_DETAILS = "edit_student_details";
export const AUTHENTICATE_EMPLOYER = "AUTHENTICATE_EMPLOYER";
export const SIGN_OUT = 'SIGN_OUT';
export const UPDATE_EDUCATION_BY_ID = 'UPDATE_EDUCATION_BY_ID';
export const ADD_EDUCATION = 'ADD_EDUCATION';
export const UPDATE_EXPERIENCE_BY_ID = 'UPDATE_EXPERIENCE_BY_ID';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const UPDATE_STUDENT_FIRST_NAME = "UPDATE_STUDENT_FIRST_NAME";
export const UPDATE_STUDENT_LAST_NAME = "UPDATE_STUDENT_LAST_NAME";
export const UPDATE_STUDENT_OBJECTIVE = "UPDATE_STUDENT_OBJECTIVE";
export const ADD_SKILL = "ADD_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const UPDATE_STUDENT_PHONENUMBER = "UPDATE_STUDENT_PHONENUMBER";
export const UPDATE_STUDENT_PROFILE_PIC = "UPDATE_STUDENT_PROFILE_PIC";
export const FETCH_STUDENT_PROFILE_PIC = "FETCH_EMPLOPYER_PROFILE_PIC";
export const UPDATE_STUDENT_PROFILE = "UPDATE_STUDENT_PROFILE";

export const EMPLOYER_DETAILS = "EMPLOYER_DETAILS";
export const UPDATE_EMPLOYER_ADDRESS = "UPDATE_EMPLOYER_ADDRESS";
export const UPDATE_EMPLOYER_PHONENUMBER = "UPDATE_EMPLOYER_PHONENUMBER";
export const UPDATE_EMPLOYER_DISCRIPTION = "UPDATE_EMPLOYER_DISCRIPTION";
export const ADD_EMPLOYER_DISCRIPTION = "ADD_EMPLOYER_DISCRIPTION";
export const UPDATE_EMPLOYER_NAME = "UPDATE_EMPLOYER_NAME";
export const UPDATE_EMPLOYER_PROFILE_PIC = "UPDATE_EMPLOYER_PROFILE_PIC";
export const FETCH_EMPLOPYER_PROFILE_PIC = "FETCH_EMPLOPYER_PROFILE_PIC";
export const UPDATE_EMPLOYER_PROFILE = "UPDATE_EMPLOYER_PROFILE";

export const GET_JOBS = "GET_JOBS";
export const ADD_JOB = "ADD_JOB";
export const UPDATE_JOB = "UPDATE_JOB";
export const FETCH_PROFILE_PICTURE_FOR_JOB = "FETCH_PROFILE_PICTURE_FOR_JOB";

export const ADD_APPLICATION = "ADD_APPLICATION";
export const UPDATE_APPLICATION = "UPDATE_APPLICATION";
export const GET_APPLICATIONS ="GET_APPLICATIONS";
export const APPLY = "APPLY";

export const ADD_EVENT = "ADD_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const GET_EVENTS ="GET_EVENTS";

export const CREATE_CONVERSATION = "CREATE_CONVERSATION";
export const ADD_MESSAGE_TO_CONVERSATION = "ADD_MESSAGE_TO_CONVERSATION";
export const GET_CONVERSATIONS = "GET_CONVERSATIONS";

export const REGISTER_FOR_EVENT = "REGISTER_FOR_EVENT";
export const GET_REGISTRATIONS ="GET_REGISTRATIONS";
export const ADD_REGISTRATION = "ADD_REGISTRATION";

export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";